name: Continuous Integration

on:
  pull_request:
    branches:
      - devel
      - feature/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: devel

      - name: Install Buf CLI
        uses: bufbuild/buf-setup-action@v1

      - name: Lint the proto files
        run: buf lint
